### ISSUE TITLE
Which convex hull algorithm is this package based on?

### ISSUE THREAD

**Issue by WuSiren** [davidavdav/CHull.jl#44]
Hi, everyone! May I ask which convex hull algorithm is this package based on (Are there any references?)? And what are the differences between this package and the convex hull algorithm introduced [here](https://juliapolyhedra.github.io/Polyhedra.jl/stable/generated/Convex%20hull%20of%20a%20set%20of%20points/#Convex-hull-of-a-set-of-points)? Which one is more efficient?

Thanks in advance!

**Comment by blegat** [comment]
You have a list of different libraries you can choose from https://juliapolyhedra.github.io/. If you use the default implementation in Polyhedra.jl, it depends whether you removing redundancy or computing the H-representation, it would help to have a code example of what you are doing.

**Comment by blegat** [comment]
Ah yes, I missed that the issue was opened on this package and not Polyhedra.jl, yest it's this one http://www.qhull.org/

**Comment by blegat** [comment]
Not aware of any library doing that. I would probably first compute the convex hull of all the points and then look at the sensitivity, ideally with a linear programming approach.
