### ISSUE TITLE
Convex Hull for N-dimensions

### ISSUE THREAD

**Issue by pnvolkmar** [davidavdav/CHull.jl#6]
p = rand(10,3)
ch = chull(p)

Throws an error that dimensions do not match.

**Comment by pnvolkmar** [comment]
Editing the chull function in src/CHull.jl to the code below takes care of it for me:


function chull{T<:Real}(x::Array{T})
    py = spatial.ConvexHull(x)
    points = convert(Array{T},py["points"])
    vertices = convert(Array{Int},py["vertices"]) + 1
    s1 = convert(Array{Array{Int,1},1},py["simplices"])
    n = length(s1)
    simplices = s1 + [ones(Int,c) for i = 1:n]
    Chull(points, vertices, simplices)
end

**Comment by davidavdav** [comment]
Thanks, 

Could you submit a Pull Request for this?  You can probably just edit the file on github and it will clone the repo for you, and you can then submit a PR from the github infrastructure.  The advantage is that you get the credits (by github) for this. 

For the simplices, you can probably write `Vector{Vector{Int}}`---that is the same.

**Comment by pnvolkmar** [comment]
Thanks, I've done what you've suggested below, but forgot the 
vector{vector{Int}} modification, sorry.
